routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('/dashboard', function () {
    return view('dashboard');
})->middleware(['auth'])->name('dashboard');


Route::prefix('admin')->namespace('App\Http\Controllers\Admin')->middleware(['auth'])->group(function() {
    
    Route::resource('permission', PermissionController::class);
    Route::resource('role', RoleController::class);
    Route::resource('user', UserController::class);

    Route::get('edit-account-info',[UserController::class,'profileInformation'])->name('admin.profile.info');
    Route::post('edit-account-info',[UserController::class,'profileInformationStore'])->name('admin.profile.info.store');
    Route::post('change-password',[UserController::class,'changePasswordStore'])->name('admin.profile.password.store');
});

require __DIR__.'/auth.php';

resources/views/layouts/backend/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    @include('layouts.backend.head')
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <?php
            $user = Auth()->user();
            ?>
        @include('layouts.backend.header',compact('user'))
        @include('layouts.backend.sidebar',compact('user'))
    @include('layouts.backend.messsage')
        @yield('content')
    </div>
    @include('layouts.backend.footer')

</body>

@include('layouts.backend.script')
</html>

resources/views/layouts/backend/error.blade.php
@if (count($errors) > 0)
<?php /*  <div class="alert alert-danger">
    <strong>Whoops!</strong> There were some problems with your input.<br><br>
    <ul>
       @foreach ($errors->all() as $error)
         <li>{{ $error }}</li>
       @endforeach
    </ul>
  </div> */?>
@endif

@if ($message = Session::get('success'))
    <div class="alert alert-success">
        <p>{{ $message }}</p>
    </div>
@endif

@if ($message = Session::get('error'))
    <div class="alert alert-error">
        <p>{{ $message }}</p>
    </div>
@endif

resources/views/layouts/backend/footer.blade.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Brought To You By <a href="https://code-projects.org/">Code-Projects</a></b>
    </div>
    <strong>Copyright &copy; {{{date('Y')}}} Attendance and Payroll System </strong>
</footer>

resources/views/layouts/backend/head.blade.php
<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<meta name="csrf-token" content="{{csrf_token()}}">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<title>Attendance and Payroll System</title>

<meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
<!-- Bootstrap 3.3.7 -->
<link rel="stylesheet" href="{{asset('/backend/bower_components/bootstrap/dist/css/bootstrap.min.css')}}">
<!-- Font Awesome -->
<link rel="stylesheet" href="{{asset('/backend/bower_components/font-awesome/css/font-awesome.min.css')}}">
<!-- Ionicons -->
<link rel="stylesheet" href="{{asset('/backend/bower_components/Ionicons/css/ionicons.min.css')}}">
<!-- Theme style -->
<link rel="stylesheet" href="{{asset('/backend/dist/css/AdminLTE.min.css')}}">
<!-- DataTables -->
<!-- <link rel="stylesheet" href="{{asset('/backend/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css')}}"> -->
<!-- daterange picker -->
<link rel="stylesheet" href="{{asset('/backend/bower_components/bootstrap-daterangepicker/daterangepicker.css')}}">
<!-- Bootstrap time Picker -->
<link rel="stylesheet" href="{{asset('/backend/plugins/timepicker/bootstrap-timepicker.min.css')}}">
<!-- bootstrap datepicker -->
<link rel="stylesheet" href="{{asset('/backend/bower_components/bootstrap-datepicker/dist/css/bootstrap-datepicker.min.css')}}">
<!-- AdminLTE Skins. Choose a skin from the css/skins
   folder instead of downloading all of them to reduce the load. -->
<link rel="stylesheet" href="{{asset('/backend/dist/css/skins/_all-skins.min.css')}}">
<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->

<!-- Google Font -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">

<style type="text/css">
    .mt20{
        margin-top:20px;
    }
.bold{
  font-weight:bold;
}

/* chart style*/
#legend ul {
  list-style: none;
}

#legend ul li {
  display: inline;
  padding-left: 30px;
  position: relative;
  margin-bottom: 4px;
  border-radius: 5px;
  padding: 2px 8px 2px 28px;
  font-size: 14px;
  cursor: default;
  -webkit-transition: background-color 200ms ease-in-out;
  -moz-transition: background-color 200ms ease-in-out;
  -o-transition: background-color 200ms ease-in-out;
  transition: background-color 200ms ease-in-out;
}

#legend li span {
  display: block;
  position: absolute;
  left: 0;
  top: 0;
  width: 20px;
  height: 100%;
  border-radius: 5px;
}
</style>

resources/views/layouts/backend/header.blade.php
<header class="main-header">
    <!-- Logo -->
    {{-- <a href="{{ route('home') }}" class="logo"> --}}
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>C</b>-P</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b></b>  {{ucFirst($user->name ?? '')}}</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ (!empty($user['photo'])) ? asset('images/'.$user['photo']) : asset('backend/images/male6.jpg')  }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ ucfirst($user['name'])  }}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ (!empty($user['photo'])) ? asset('images/'.$user['photo']) : asset('backend/images/male6.jpg') }}" class="img-circle" alt="User Image">
                            <p>
                                {{ ucfirst($user['name'])  ?? 'Superadmin' }}
                                <small>Member since {{ \Carbon\Carbon::parse($user['created_on'])->format('M. Y') }}</small>
                            </p>
                        </li>
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#profile" data-toggle="modal" class="btn btn-default btn-flat" id="admin_profile">Update</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                              document.getElementById('logout-form').submit();">
                                 {{ __('Logout') }}
                             </a>
                             <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                 @csrf
                             </form>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/backend/messsage.blade.php
<!-- <link href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0- 
     alpha/css/bootstrap.css" rel="stylesheet">
    
 -->

    <!-- <link rel="stylesheet" type="text/css" 
     href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
   -->
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
   
   <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/css/toastr.css" rel="stylesheet" />
   <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.0.1/js/toastr.js"></script>
<script>
 
  @if(Session::has('success'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.success("{{ session('success') }}");
  @endif

  @if(Session::has('error'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.error("{{ session('error') }}");
  @endif

  @if(Session::has('info'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.info("{{ session('info') }}");
  @endif

  @if(Session::has('warning'))
  toastr.options =
  {
    "closeButton" : true,
    "progressBar" : true
  }
        toastr.warning("{{ session('warning') }}");
  @endif
</script>

resources/views/layouts/backend/script.blade.php
<!-- jQuery 3 -->
<script src="{{asset('/backend/bower_components/jquery/dist/jquery.min.js')}}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{{asset('/backend/bower_components/jquery-ui/jquery-ui.min.js')}}"></script>
<!-- DataTables -->
<!-- <script src="{{asset('/backend/bower_components/datatables.net/js/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('/backend/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js')}}"></script> -->
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{{asset('/backend/bower_components/bootstrap/dist/js/bootstrap.min.js')}}"></script>
<!-- Morris.js charts -->
{{-- <script src="{{asset('/backend/bower_components/raphael/raphael.min.js')}}"></script> --}}
{{-- <script src="{{asset('/backend/bower_components/morris.js/morris.min.js')}}"></script> --}}
<!-- ChartJS -->
{{-- <script src="{{asset('/backend/bower_components/chart.js/Chart.js')}}"></script> --}}
<!-- Sparkline -->
{{-- <script src="{{asset('/backend/bower_components/jquery-sparkline/dist/jquery.sparkline.min.js')}}"></script> --}}
<!-- jvectormap -->
{{-- <script src="{{asset('/backend/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js')}}"></script>
<script src="{{asset('/backend/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script> --}}
<!-- jQuery Knob Chart -->
{{-- <script src="{{asset('/backend/bower_components/jquery-knob/dist/jquery.knob.min.js')}}"></script> --}}
<!-- daterangepicker -->
<script src="{{asset('/backend/bower_components/moment/min/moment.min.js')}}"></script>
<script src="{{asset('/backend/bower_components/bootstrap-daterangepicker/daterangepicker.js')}}"></script>
<!-- datepicker -->
<script src="{{asset('/backend/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')}}"></script>
<!-- bootstrap time picker -->
<script src="{{asset('/backend/plugins/timepicker/bootstrap-timepicker.min.js')}}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{{asset('/backend/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js')}}"></script>
<!-- Slimscroll -->
<script src="{{asset('/backend/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')}}"></script>
<!-- FastClick -->
<script src="{{asset('/backend/bower_components/fastclick/lib/fastclick.js')}}"></script>
<!-- AdminLTE App -->
<script src="{{asset('/backend/dist/js/adminlte.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
{{-- <script src="{{asset('/backend/dist/js/pages/dashboard.js')}}"></script> --}}
<!-- AdminLTE for demo purposes -->
{{-- <script src="{{asset('/backend/dist/js/demo.js')}}"></script> --}}
@stack('scripts')
<script>

  function editRecord($this){
    var route = $this.getAttribute('data-url');
    var id = $this.getAttribute('data-id');
    var model = $this.getAttribute('data-model');
    AjaxCall(route,model,'GET','html');
  }

  function showRecord($this){
    var route = $this.getAttribute('data-url');
    var id = $this.getAttribute('data-id');
    var model = $this.getAttribute('data-model');
    AjaxCall(route,model,'GET','html');
  }

  function deleteRecord($this){
    var route = $this.getAttribute('data-url');
    var id = $this.getAttribute('data-id');
    var model = $this.getAttribute('data-model');
    AjaxCall(route,model,'POST','JSON');
  }

  function AjaxCall(route,modelId,method,dataType){
    $('#'+modelId).modal('show');
    // Make an AJAX POST request
        $.ajax({
            type: method,
            url: route,
            data: '',
            dataType: dataType,
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            success: function(response) {
              if(dataType=='html')
              {
                $('#'+modelId).html(response);
              }
            },
            error: function(xhr, status, error) {
                console.error(error);
            }
        });


     }

  $(document).ready(function() {

  $(".editRecord1").on("click", function(e) {
    alert("First alert: Click event detected."); // Debugging line 1

    e.preventDefault();

    alert("Second alert: Default action prevented."); // Debugging line 2

    modelId = $(this).attr("data-model");
    route = $(this).attr("data-url");

    alert("Third alert: Model ID - " + modelId + ", Route - " + route); // Debugging line 3

    AjaxCall(route, modelId, 'GET');
  });
});






$(function(){
  /** add active class and stay opened when selected */
  var url = window.location;

  // for sidebar menu entirely but not cover treeview
  $('ul.sidebar-menu a').filter(function() {
     return this.href == url;
  }).parent().addClass('active');

  // for treeview
  $('ul.treeview-menu a').filter(function() {
     return this.href == url;
  }).parentsUntil(".sidebar-menu > .treeview-menu").addClass('active');



});

</script>

resources/views/layouts/backend/sidebar.blade.php
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="<?php echo (!empty($user['photo'])) ? '../images/'.$user['photo'] : asset('backend/images/male6.jpg'); ?>" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p><?php echo $user['firstname'].' '.$user['lastname']; ?></p>
          <a><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">REPORTS</li>
        <li class=""><a href="{{url('dashboard')}}"><i class="fa fa-dashboard"></i> <span>Dashboard</span></a></li>
        <li class="header">MANAGE</li>

        @role('super-admin')
        <li class=""><a href="{{route('role.index')}}"><i class="fa fa-dashboard"></i> <span>Roles</span></a></li>
        <li class=""><a href="{{route('permission.index')}}"><i class="fa fa-dashboard"></i> <span>Permission</span></a></li>
        <li class=""><a href="{{route('user.index')}}"><i class="fa fa-dashboard"></i> <span>Users</span></a></li>
        @endrole
{{--
                <li {{ request()->is('roles') || request()->is('roles/*') ? 'active' : '' }}><a href="{{url('roles')}}"><i class="fa fa-calendar"></i> <span>Role</span></a></li>
                <li><a href="{{url('products')}}"><i class="fa fa-calendar"></i> <span>Product</span></a></li>
                <li {{ request()->is('users') || request()->is('users/*') ? 'active' : '' }}><a href="{{url('users')}}"><i class="fa fa-calendar"></i> <span>User Management</span></a></li> --}}


        {{-- <li class="treeview">
          <a href="#">
            <i class="fa fa-users"></i>
            <span>Employees</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            <li><a href="employee.php"><i class="fa fa-circle-o"></i> Employee List</a></li>
            <li><a href="overtime.php"><i class="fa fa-circle-o"></i> Overtime</a></li>
            <li><a href="cashadvance.php"><i class="fa fa-circle-o"></i> Cash Advance</a></li>
            <li><a href="schedule.php"><i class="fa fa-circle-o"></i> Schedules</a></li>
          </ul>
        </li> --}}
        {{-- <li><a href="deduction.php"><i class="fa fa-file-text"></i> Deductions</a></li>
        <li><a href="position.php"><i class="fa fa-suitcase"></i> Positions</a></li>
        <li class="header">PRINTABLES</li>
        <li><a href="payroll.php"><i class="fa fa-files-o"></i> <span>Payroll</span></a></li>
        <li><a href="schedule_employee.php"><i class="fa fa-clock-o"></i> <span>Schedule</span></a></li> --}}
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>